# Generated by Django 3.2.3 on 2021-06-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('S', 'SHIRT'), ('SW', 'SHIRT WEAR'), ('OW', 'OUT WEAR')], max_length=2)),
                ('label', models.CharField(choices=[('P', 'PRIMARY'), ('S', 'SEONDARY'), ('D', 'DANGER')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
