# Generated by Django 3.1.7 on 2021-06-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20210612_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sub_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
