# Generated by Django 3.1.7 on 2021-06-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_confirmedticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedticket',
            name='item',
        ),
        migrations.RemoveField(
            model_name='confirmedticket',
            name='sub_total',
        ),
        migrations.AddField(
            model_name='confirmedticket',
            name='address',
            field=models.CharField(default='https://github.com/sibi1999/sample_images/blob/master/shirt/sh1.jpg?raw=true', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmedticket',
            name='country',
            field=models.CharField(default='India', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmedticket',
            name='email',
            field=models.CharField(default='sksibi123@gmail.com', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmedticket',
            name='name',
            field=models.CharField(default='x', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmedticket',
            name='product_name',
            field=models.CharField(default='shirt', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmedticket',
            name='product_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='confirmedticket',
            name='state',
            field=models.CharField(default='TamilNadu', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmedticket',
            name='zip',
            field=models.CharField(default=603202, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='img_url',
            field=models.CharField(default='https://github.com/sibi1999/sample_images/blob/master/shirt/sh1.jpg?raw=true', max_length=1000),
            preserve_default=False,
        ),
    ]
