# Generated by Django 3.1.7 on 2021-06-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20210613_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedticket',
            name='address',
            field=models.CharField(default='a', max_length=1000),
        ),
    ]
