# Generated by Django 3.2.3 on 2021-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_confirmedticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'SHIRT'), ('SW', 'SPORT WEAR'), ('OW', 'OUT WEAR')], max_length=2),
        ),
    ]
