# Generated by Django 3.2.3 on 2021-06-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancellation', '0002_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
