# Generated by Django 3.2.3 on 2021-06-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancellation', '0003_delete_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
